use crate::diff::{Review, Risk};

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

/// Render a review artifact containing explanations but no executable SQL.
pub fn markdown(review: &Review) -> String {
    let mut out = String::new();
    out.push_str("# Schema drift review\n\n");
    out.push_str(&format!(
        "> {} comparison · expected `{}` · observed `{}`\n\n",
        review.dialect, review.before_captured_at, review.after_captured_at
    ));
    if review.summary.total == 0 {
        out.push_str("## No drift detected\n\nThe captured schema metadata is identical. No repair is suggested.\n");
        return out;
    }
    out.push_str("## Review summary\n\n");
    out.push_str(&format!(
        "- **{}** total differences\n- **{}** high risk · **{}** medium · **{}** low\n- **{}** potentially destructive\n- **{}** potentially ORM-invisible\n\n",
        review.summary.total,
        review.summary.high,
        review.summary.medium,
        review.summary.low,
        review.summary.destructive,
        review.summary.orm_invisible
    ));
    if review.summary.high > 0 {
        out.push_str(
            "> **Pause before repair.** High-risk drift needs an owner, a backup/rollback plan, and deploy-order review. This report intentionally contains no executable repair SQL.\n\n",
        );
    }
    out.push_str("## Classified differences\n\n");
    out.push_str("| Risk | Change | Object | Flags | Likely owner | Explanation |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for change in &review.changes {
        let mut flags = Vec::new();
        if change.destructive {
            flags.push("destructive");
        }
        if change.orm_invisible {
            flags.push("ORM-invisible");
        }
        if flags.is_empty() {
            flags.push("review");
        }
        out.push_str(&format!(
            "| {} | {} {} | `{}` | {} | {} | {} |\n",
            change.risk,
            change.change,
            change.object_kind,
            escape_cell(&change.object),
            flags.join(", "),
            escape_cell(&change.likely_owner),
            escape_cell(&change.explanation),
        ));
    }
    out.push_str("\n## Repair checklist\n\n");
    out.push_str("1. Identify the owning migration or out-of-band DDL for each difference.\n");
    out.push_str("2. Confirm application and ORM expectations against the observed schema.\n");
    out.push_str("3. Prepare a reversible migration and backup plan outside this tool.\n");
    out.push_str("4. Re-snapshot after the approved repair and expect an empty review.\n\n");
    out.push_str(
        "_Generated by Schema Drift Snapshot. Metadata only; no row data was inspected._\n",
    );
    out
}

pub fn severity_label(risk: Risk) -> &'static str {
    match risk {
        Risk::Low => "low",
        Risk::Medium => "medium",
        Risk::High => "high",
    }
}

#[cfg(test)]
mod tests {
    use crate::diff::{Review, Summary};

    use super::*;

    #[test]
    fn empty_review_has_clear_empty_state() {
        let report = markdown(&Review {
            dialect: "postgresql".to_owned(),
            before_captured_at: "a".to_owned(),
            after_captured_at: "b".to_owned(),
            summary: Summary {
                total: 0,
                high: 0,
                medium: 0,
                low: 0,
                destructive: 0,
                orm_invisible: 0,
            },
            changes: vec![],
        });
        assert!(report.contains("No drift detected"));
        assert!(!report.contains("repair SQL"));
    }
}
